/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_num1 = new javax.swing.JLabel();
        lbl_num2 = new javax.swing.JLabel();
        txt_num1 = new javax.swing.JTextField();
        txt_num2 = new javax.swing.JTextField();
        btn_mais = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_vezes = new javax.swing.JButton();
        btn_dividir = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();
        btn_habilitar = new javax.swing.JButton();
        btn_desabilitar = new javax.swing.JButton();
        btn_ocultar = new javax.swing.JButton();
        btn_exibir = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();
        lbl_desenv = new javax.swing.JLabel();
        lbl_calculadora = new javax.swing.JLabel();
        lbl_resultado = new javax.swing.JLabel();
        lbl_result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbl_num1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lbl_num1.setText("1° Número");

        lbl_num2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_num2.setText("2° Número");

        txt_num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_num1ActionPerformed(evt);
            }
        });

        btn_mais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_mais.setText("+");
        btn_mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_maisActionPerformed(evt);
            }
        });

        btn_menos.setText("-");
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_vezes.setText("*");
        btn_vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vezesActionPerformed(evt);
            }
        });

        btn_dividir.setText("/");
        btn_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dividirActionPerformed(evt);
            }
        });

        btn_limpar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        btn_habilitar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_habilitar.setText("Habilitar");
        btn_habilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_habilitarActionPerformed(evt);
            }
        });

        btn_desabilitar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_desabilitar.setText("Desabilitar");
        btn_desabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desabilitarActionPerformed(evt);
            }
        });

        btn_ocultar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_ocultar.setText("Ocultar");
        btn_ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ocultarActionPerformed(evt);
            }
        });

        btn_exibir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_exibir.setText("Exibir");
        btn_exibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exibirActionPerformed(evt);
            }
        });

        btn_sair.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btn_sair.setText("Sair");
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        lbl_desenv.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        lbl_desenv.setText("Desenvolvido pela aluna Gabriela Aguiar - 2DS");

        lbl_calculadora.setFont(new java.awt.Font("Humanst521 Lt BT", 1, 24)); // NOI18N
        lbl_calculadora.setForeground(new java.awt.Color(0, 102, 102));
        lbl_calculadora.setText("Calculadora");

        lbl_resultado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_resultado.setForeground(new java.awt.Color(204, 0, 51));
        lbl_resultado.setText("Resultado:");

        lbl_result.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_habilitar)
                                    .addGap(41, 41, 41)
                                    .addComponent(btn_desabilitar)
                                    .addGap(38, 38, 38)
                                    .addComponent(btn_ocultar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                    .addComponent(btn_exibir))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbl_desenv)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_sair)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_resultado)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(302, 302, 302)
                                            .addComponent(btn_limpar))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lbl_result))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_num2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_num2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_num1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_num1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(134, 134, 134)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_vezes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_mais, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_dividir, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                        .addComponent(btn_menos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(lbl_calculadora)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbl_calculadora)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_num1)
                    .addComponent(txt_num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mais)
                    .addComponent(btn_menos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_num2)
                    .addComponent(txt_num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vezes)
                    .addComponent(btn_dividir))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btn_limpar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_resultado)
                            .addComponent(lbl_result))))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_habilitar)
                    .addComponent(btn_desabilitar)
                    .addComponent(btn_ocultar)
                    .addComponent(btn_exibir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_desenv)
                    .addComponent(btn_sair))
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_num1ActionPerformed
        
        
    }//GEN-LAST:event_txt_num1ActionPerformed

    private void btn_maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_maisActionPerformed
        double a = Double.parseDouble(txt_num1.getText());
        double b = Double.parseDouble(txt_num2.getText());
        double c = a + b;
        
        lbl_result.setText("" + c);
    }//GEN-LAST:event_btn_maisActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        txt_num1.setText(" ");
        txt_num2.setText(" ");
        lbl_result.setText(" ");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_habilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_habilitarActionPerformed
        lbl_result.setEnabled(true);
    }//GEN-LAST:event_btn_habilitarActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        double a = Double.parseDouble(txt_num1.getText());
        double b = Double.parseDouble(txt_num2.getText());
        double c = a - b;
        
        lbl_result.setText("" + c);
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_vezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vezesActionPerformed
        double a = Double.parseDouble(txt_num1.getText());
        double b = Double.parseDouble(txt_num2.getText());
        double c = a * b;
        
        lbl_result.setText("" + c);
    }//GEN-LAST:event_btn_vezesActionPerformed

    private void btn_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dividirActionPerformed
        double a = Double.parseDouble(txt_num1.getText());
        double b = Double.parseDouble(txt_num2.getText());
        double c = a / b;
        
        lbl_result.setText("" + c);
    }//GEN-LAST:event_btn_dividirActionPerformed

    private void btn_ocultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ocultarActionPerformed
        lbl_result.setVisible(false);
    }//GEN-LAST:event_btn_ocultarActionPerformed

    private void btn_desabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desabilitarActionPerformed
        lbl_result.setEnabled(false);
    }//GEN-LAST:event_btn_desabilitarActionPerformed

    private void btn_exibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exibirActionPerformed
        lbl_result.setVisible(true);
    }//GEN-LAST:event_btn_exibirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_desabilitar;
    private javax.swing.JButton btn_dividir;
    private javax.swing.JButton btn_exibir;
    private javax.swing.JButton btn_habilitar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_mais;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_ocultar;
    private javax.swing.JButton btn_sair;
    private javax.swing.JButton btn_vezes;
    private javax.swing.JLabel lbl_calculadora;
    private javax.swing.JLabel lbl_desenv;
    private javax.swing.JLabel lbl_num1;
    private javax.swing.JLabel lbl_num2;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JTextField txt_num1;
    private javax.swing.JTextField txt_num2;
    // End of variables declaration//GEN-END:variables
}
